image: atlassian/default-image:2

pipelines:
    branches:
        master:
            - step:
                name: Build
                caches:
                  - node
                script:
                  - zip -r askHowApp.zip .
                artifacts:
                  - askHowApp.zip
            - step:
                name: Upload to S3
                services: 
                  - docker
                script:
                  - pipe: atlassian/aws-code-deploy:1.1.1
                    variables:
                      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                      APPLICATION_NAME: $APPLICATION_NAME
                      S3_BUCKET: $S3_BUCKET
                      COMMAND: 'upload'
                      ZIP_FILE: 'askHowApp.zip'
                      VERSION_LABEL: 'askHowApp-1.0.0'
            - step:
                name: Deploy using Code Deploy
                services: 
                  - docker
                script:
                  - pipe: atlassian/aws-code-deploy:1.1.1
                    variables:
                      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                      APPLICATION_NAME: $APPLICATION_NAME
                      DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                      S3_BUCKET: $S3_BUCKET
                      COMMAND: 'deploy'
                      WAIT: 'true'
                      VERSION_LABEL: 'askHowApp-1.0.0'
                      IGNORE_APPLICATION_STOP_FAILURES: 'true'
                      FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
definitions:
  caches:
    nextcache: .next/cache