const router = require('express-promise-router')()
const questions = require('./question.routes')
const users = require('./users.routes')
const tags = require('./tags.routes')
const categories = require('./category.routes')
const setting = require('./setting.routes')
const subject = require('./subject.routes')
const follow = require('./follower.routes')
const search = require('./search.routes')
const course = require('./course.routes')
const comment = require('./comment.routes')
const udemy = require('./udemy.routes')
const udacity = require('./udacity.routes')
const lynda = require('./lynda.routes')
const notification = require('./notification.routes')

router.use('/', questions)
router.use('/', users)
router.use('/', tags)
router.use('/', categories)
router.use('/', setting)
router.use('/', subject)
router.use('/', follow)
router.use('/', search)
router.use('/', course)
router.use('/', comment)
router.use('/', udemy)
router.use('/', notification)
router.use('/', udacity)
router.use('/', lynda)

module.exports = router
